/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BmpToWebpRouteImport } from './routes/bmp-to-webp'
import { Route as GifToWebpRouteImport } from './routes/gif-to-webp'
import { Route as JpegToWebpRouteImport } from './routes/jpeg-to-webp'
import { Route as JpgToWebpRouteImport } from './routes/jpg-to-webp'
import { Route as MetaTagGeneratorRouteImport } from './routes/meta-tag-generator'
import { Route as OpenGraphGeneratorRouteImport } from './routes/open-graph-generator'
import { Route as PngToWebpRouteImport } from './routes/png-to-webp'
import { Route as RobotsTxtGeneratorRouteImport } from './routes/robots-txt-generator'
import { Route as SpeechToTextRouteImport } from './routes/speech-to-text'
import { Route as SvgToWebpRouteImport } from './routes/svg-to-webp'
import { Route as TextToSpeechRouteImport } from './routes/text-to-speech'
import { Route as WebpConverterRouteImport } from './routes/webp-converter'
import { Route as XmlSitemapGeneratorRouteImport } from './routes/xml-sitemap-generator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BmpToWebpRoute = BmpToWebpRouteImport.update({
  id: '/bmp-to-webp',
  path: '/bmp-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const GifToWebpRoute = GifToWebpRouteImport.update({
  id: '/gif-to-webp',
  path: '/gif-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const JpegToWebpRoute = JpegToWebpRouteImport.update({
  id: '/jpeg-to-webp',
  path: '/jpeg-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToWebpRoute = JpgToWebpRouteImport.update({
  id: '/jpg-to-webp',
  path: '/jpg-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaTagGeneratorRoute = MetaTagGeneratorRouteImport.update({
  id: '/meta-tag-generator',
  path: '/meta-tag-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenGraphGeneratorRoute = OpenGraphGeneratorRouteImport.update({
  id: '/open-graph-generator',
  path: '/open-graph-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PngToWebpRoute = PngToWebpRouteImport.update({
  id: '/png-to-webp',
  path: '/png-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtGeneratorRoute = RobotsTxtGeneratorRouteImport.update({
  id: '/robots-txt-generator',
  path: '/robots-txt-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechToTextRoute = SpeechToTextRouteImport.update({
  id: '/speech-to-text',
  path: '/speech-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgToWebpRoute = SvgToWebpRouteImport.update({
  id: '/svg-to-webp',
  path: '/svg-to-webp',
  getParentRoute: () => rootRouteImport,
} as any)
const TextToSpeechRoute = TextToSpeechRouteImport.update({
  id: '/text-to-speech',
  path: '/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const WebpConverterRoute = WebpConverterRouteImport.update({
  id: '/webp-converter',
  path: '/webp-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const XmlSitemapGeneratorRoute = XmlSitemapGeneratorRouteImport.update({
  id: '/xml-sitemap-generator',
  path: '/xml-sitemap-generator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bmp-to-webp': typeof BmpToWebpRoute
  '/gif-to-webp': typeof GifToWebpRoute
  '/jpeg-to-webp': typeof JpegToWebpRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/meta-tag-generator': typeof MetaTagGeneratorRoute
  '/open-graph-generator': typeof OpenGraphGeneratorRoute
  '/png-to-webp': typeof PngToWebpRoute
  '/robots-txt-generator': typeof RobotsTxtGeneratorRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/svg-to-webp': typeof SvgToWebpRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/webp-converter': typeof WebpConverterRoute
  '/xml-sitemap-generator': typeof XmlSitemapGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bmp-to-webp': typeof BmpToWebpRoute
  '/gif-to-webp': typeof GifToWebpRoute
  '/jpeg-to-webp': typeof JpegToWebpRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/meta-tag-generator': typeof MetaTagGeneratorRoute
  '/open-graph-generator': typeof OpenGraphGeneratorRoute
  '/png-to-webp': typeof PngToWebpRoute
  '/robots-txt-generator': typeof RobotsTxtGeneratorRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/svg-to-webp': typeof SvgToWebpRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/webp-converter': typeof WebpConverterRoute
  '/xml-sitemap-generator': typeof XmlSitemapGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bmp-to-webp': typeof BmpToWebpRoute
  '/gif-to-webp': typeof GifToWebpRoute
  '/jpeg-to-webp': typeof JpegToWebpRoute
  '/jpg-to-webp': typeof JpgToWebpRoute
  '/meta-tag-generator': typeof MetaTagGeneratorRoute
  '/open-graph-generator': typeof OpenGraphGeneratorRoute
  '/png-to-webp': typeof PngToWebpRoute
  '/robots-txt-generator': typeof RobotsTxtGeneratorRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/svg-to-webp': typeof SvgToWebpRoute
  '/text-to-speech': typeof TextToSpeechRoute
  '/webp-converter': typeof WebpConverterRoute
  '/xml-sitemap-generator': typeof XmlSitemapGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bmp-to-webp'
    | '/gif-to-webp'
    | '/jpeg-to-webp'
    | '/jpg-to-webp'
    | '/meta-tag-generator'
    | '/open-graph-generator'
    | '/png-to-webp'
    | '/robots-txt-generator'
    | '/speech-to-text'
    | '/svg-to-webp'
    | '/text-to-speech'
    | '/webp-converter'
    | '/xml-sitemap-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bmp-to-webp'
    | '/gif-to-webp'
    | '/jpeg-to-webp'
    | '/jpg-to-webp'
    | '/meta-tag-generator'
    | '/open-graph-generator'
    | '/png-to-webp'
    | '/robots-txt-generator'
    | '/speech-to-text'
    | '/svg-to-webp'
    | '/text-to-speech'
    | '/webp-converter'
    | '/xml-sitemap-generator'
  id:
    | '__root__'
    | '/'
    | '/bmp-to-webp'
    | '/gif-to-webp'
    | '/jpeg-to-webp'
    | '/jpg-to-webp'
    | '/meta-tag-generator'
    | '/open-graph-generator'
    | '/png-to-webp'
    | '/robots-txt-generator'
    | '/speech-to-text'
    | '/svg-to-webp'
    | '/text-to-speech'
    | '/webp-converter'
    | '/xml-sitemap-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BmpToWebpRoute: typeof BmpToWebpRoute
  GifToWebpRoute: typeof GifToWebpRoute
  JpegToWebpRoute: typeof JpegToWebpRoute
  JpgToWebpRoute: typeof JpgToWebpRoute
  MetaTagGeneratorRoute: typeof MetaTagGeneratorRoute
  OpenGraphGeneratorRoute: typeof OpenGraphGeneratorRoute
  PngToWebpRoute: typeof PngToWebpRoute
  RobotsTxtGeneratorRoute: typeof RobotsTxtGeneratorRoute
  SpeechToTextRoute: typeof SpeechToTextRoute
  SvgToWebpRoute: typeof SvgToWebpRoute
  TextToSpeechRoute: typeof TextToSpeechRoute
  WebpConverterRoute: typeof WebpConverterRoute
  XmlSitemapGeneratorRoute: typeof XmlSitemapGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmp-to-webp': {
      id: '/bmp-to-webp'
      path: '/bmp-to-webp'
      fullPath: '/bmp-to-webp'
      preLoaderRoute: typeof BmpToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gif-to-webp': {
      id: '/gif-to-webp'
      path: '/gif-to-webp'
      fullPath: '/gif-to-webp'
      preLoaderRoute: typeof GifToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpeg-to-webp': {
      id: '/jpeg-to-webp'
      path: '/jpeg-to-webp'
      fullPath: '/jpeg-to-webp'
      preLoaderRoute: typeof JpegToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-webp': {
      id: '/jpg-to-webp'
      path: '/jpg-to-webp'
      fullPath: '/jpg-to-webp'
      preLoaderRoute: typeof JpgToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-tag-generator': {
      id: '/meta-tag-generator'
      path: '/meta-tag-generator'
      fullPath: '/meta-tag-generator'
      preLoaderRoute: typeof MetaTagGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-graph-generator': {
      id: '/open-graph-generator'
      path: '/open-graph-generator'
      fullPath: '/open-graph-generator'
      preLoaderRoute: typeof OpenGraphGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/png-to-webp': {
      id: '/png-to-webp'
      path: '/png-to-webp'
      fullPath: '/png-to-webp'
      preLoaderRoute: typeof PngToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots-txt-generator': {
      id: '/robots-txt-generator'
      path: '/robots-txt-generator'
      fullPath: '/robots-txt-generator'
      preLoaderRoute: typeof RobotsTxtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-to-text': {
      id: '/speech-to-text'
      path: '/speech-to-text'
      fullPath: '/speech-to-text'
      preLoaderRoute: typeof SpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-to-webp': {
      id: '/svg-to-webp'
      path: '/svg-to-webp'
      fullPath: '/svg-to-webp'
      preLoaderRoute: typeof SvgToWebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-to-speech': {
      id: '/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof TextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webp-converter': {
      id: '/webp-converter'
      path: '/webp-converter'
      fullPath: '/webp-converter'
      preLoaderRoute: typeof WebpConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xml-sitemap-generator': {
      id: '/xml-sitemap-generator'
      path: '/xml-sitemap-generator'
      fullPath: '/xml-sitemap-generator'
      preLoaderRoute: typeof XmlSitemapGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BmpToWebpRoute: BmpToWebpRoute,
  GifToWebpRoute: GifToWebpRoute,
  JpegToWebpRoute: JpegToWebpRoute,
  JpgToWebpRoute: JpgToWebpRoute,
  MetaTagGeneratorRoute: MetaTagGeneratorRoute,
  OpenGraphGeneratorRoute: OpenGraphGeneratorRoute,
  PngToWebpRoute: PngToWebpRoute,
  RobotsTxtGeneratorRoute: RobotsTxtGeneratorRoute,
  SpeechToTextRoute: SpeechToTextRoute,
  SvgToWebpRoute: SvgToWebpRoute,
  TextToSpeechRoute: TextToSpeechRoute,
  WebpConverterRoute: WebpConverterRoute,
  XmlSitemapGeneratorRoute: XmlSitemapGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
